### ISSUE TITLE
Document format is changed

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-editor/GroupDocs.Editor-for-.NET#34] opened 2022-01-04 21:15 UTC
This issue is raised in https://forum.groupdocs.com/t/encountered-an-error-when-saving-document-in-editor-demo/10597/2

Hi,

Please find the sample/source file and screenshots attached. Although this issue occurs for all the source files. 
The issue is, when we add text , highlight the text and save it. The format of the document is changed. Doesn't matter is license is applied or not. 
Could you please take a look?

Thanks 
[screenshots.zip](https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET/files/7810439/screenshots.zip)

**Comment by denis-gvardionov** [comment] 2022-03-01 00:59
I have read the original forum thread and have investigated the described scenario with provided input sample document ([found here](https://forum.groupdocs.com/t/encountered-an-error-when-saving-document-in-editor-demo/10597)). From what I can see the problem is regarding roundtrip conversion - when input DOCX document is opened for editing in GitHub sample demo WebForms application and then saved back to the DOCX format without any actual editing of the content, and the resultant version has incorrect content width - it is like "tighten" from left and right sides. I've tried to reproduce it using GroupDocs.Editor for .NET library itself, without using a GitHub-provided WebForms web application and was not able to reproduce it. From this I'm making a conclusion that there is something wrong in the GitHub sample demo WebForms application, but not in the GroupDocs.Editor for .NET library itself. So you need to ping someone from support team, I guess, who is responsible for the exactly GitHub sample demo.

**Comment by denis-gvardionov** [comment] 2022-05-02 09:01
@atirtahirgroupdocs 
@stupakviktor 
@yevgen-nykytenko 

Issue with corrupted document layout during its saving is solved. Updated sample project can be downloaded here: https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET/tree/master/Demos/WebForms

If you want to manually update the previously downloaded un-updated project please notice the next steps:
1) Update a "GroupDocs.Editor for .NET" NuGet package to the version `22.3.2-alpha-20220404065929` or higher, or wait until the official version of GroupDocs.Editor for .NET will be released (must be newer then 21.10).
2) If you want to use official NuGet channel "NuGet official test package source" along with beta-version of "GroupDocs.Editor for .NET" `22.3.2-alpha-20220404065929`, then in the "Package Manager Settings" you should add a new "packageSources":
`<add key="NuGet official test package source" value="https://int.nugettest.org/api/v2" />`
This will allow to use beta-packages in the official NuGet channel.

**Closed** 2024-07-04 12:38 UTC
Labels: bug
